language: node_js
node_js: 
  - 14
before_script: 
  - npm install @11ty/eleventy -g
script: npx @11ty/eleventy --pathprefix="/generative-art"
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on: 
    branch: master